# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cdv5AMLE2bqnBTYUDnYR5NVudRM3iBCY
"""

!pip3 install torch torchvision torchaudio

!pip install easyocr

import easyocr
import cv2
from matplotlib import pyplot as plt
import numpy as np

img_path = "/content/wipro.png"
reader = easyocr.Reader(['en'], gpu=False)
result = reader.readtext(img_path)
res_final = [result[a][-2] for a in range(len(result))]
res_final = " ".join(res_final)
res_final

import difflib  
from difflib import SequenceMatcher

str_2 = "wip##ro"
my_seq = SequenceMatcher(a = res_final, b = str_2).ratio()
my_seq

